//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribution
    {
        public int Id { get; set; }
        public string Nhi { get; set; }
        public int WardId { get; set; }
        public int PharmacistId { get; set; }
        public System.DateTime Date { get; set; }
        public int StaffInvolvedId { get; set; }
        public int MedicationId1 { get; set; }
        public Nullable<int> MedicationId2 { get; set; }
        public int OutcomeId { get; set; }
        public int StageId { get; set; }
        public int TimeFrameId { get; set; }
        public string Details { get; set; }
        public int ContributionTypeId { get; set; }
    
        public virtual ContributionType ContributionType { get; set; }
        public virtual Medication Medication1 { get; set; }
        public virtual Medication Medication2 { get; set; }
        public virtual Outcome Outcome { get; set; }
        public virtual Pharmacist Pharmacist { get; set; }
        public virtual StaffType StaffType { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual TimeFrame TimeFrame { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
