//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterventionType
    {
        public InterventionType()
        {
            this.Interventions = new HashSet<Intervention>();
        }
    
        public int Id { get; set; }
        public int InterventionTypeCategoryId { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Intervention> Interventions { get; set; }
        public virtual InterventionTypeCategory InterventionTypeCategory { get; set; }
    }
}
