//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kpi
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int WardId { get; set; }
        public string Notes { get; set; }
        public int MedicationChartsReviewed { get; set; }
        public int MedicinesReconciliationsMedical { get; set; }
        public int MedicinesReconciliationsSurgical { get; set; }
        public int MedicinesReconciliationsOther { get; set; }
        public int YellowCardsCompleted { get; set; }
        public int YellowCardsCompletedAndCounselled { get; set; }
        public int WarfarinCounselling { get; set; }
        public int SelfMedication { get; set; }
        public int DischargeOrderReview { get; set; }
        public int CommunityLiaison { get; set; }
        public int MedicineEducationTalks { get; set; }
        public int PharmacistId { get; set; }
    
        public virtual Ward Ward { get; set; }
        public virtual Pharmacist Pharmacist { get; set; }
    }
}
