//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public Medication()
        {
            this.Interventions1 = new HashSet<Intervention>();
            this.Interventions11 = new HashSet<Intervention>();
            this.Contributions = new HashSet<Contribution>();
            this.Contributions1 = new HashSet<Contribution>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Intervention> Interventions1 { get; set; }
        public virtual ICollection<Intervention> Interventions11 { get; set; }
        public virtual ICollection<Contribution> Contributions { get; set; }
        public virtual ICollection<Contribution> Contributions1 { get; set; }
    }
}
