//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffType
    {
        public StaffType()
        {
            this.Interventions = new HashSet<Intervention>();
            this.Contributions = new HashSet<Contribution>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Intervention> Interventions { get; set; }
        public virtual ICollection<Contribution> Contributions { get; set; }
    }
}
