//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacyInterventionsEntities : DbContext
    {
        public PharmacyInterventionsEntities()
            : base("name=PharmacyInterventionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<InterventionGrade> InterventionGrades { get; set; }
        public DbSet<Intervention> Interventions { get; set; }
        public DbSet<InterventionType> InterventionTypes { get; set; }
        public DbSet<InterventionTypeCategory> InterventionTypeCategories { get; set; }
        public DbSet<Medication> Medications { get; set; }
        public DbSet<Pharmacist> Pharmacists { get; set; }
        public DbSet<Ward> Wards { get; set; }
        public DbSet<Outcome> Outcomes { get; set; }
        public DbSet<StaffType> StaffTypes { get; set; }
        public DbSet<Stage> Stages { get; set; }
        public DbSet<TimeFrame> TimeFrames { get; set; }
        public DbSet<Contribution> Contributions { get; set; }
        public DbSet<ContributionType> ContributionTypes { get; set; }
        public DbSet<Kpi> Kpis { get; set; }
    }
}
